# Generated by Django 4.2 on 2023-10-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_texttext_fichier_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttext',
            name='fichier_audio',
            field=models.BinaryField(default=b'\x00\x01\x02\x03'),
        ),
    ]
