# Generated by Django 4.2 on 2023-10-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_texttext_fichier_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttext',
            name='fichier_audio',
        ),
        migrations.AddField(
            model_name='texttext',
            name='audioURL',
            field=models.URLField(default=''),
        ),
    ]
