# Generated by Django 4.2 on 2023-10-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_texttext_fichier_audio_texttext_audiourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttext',
            name='audioURL',
            field=models.URLField(default=b''),
        ),
    ]
