# Generated by Django 4.2 on 2023-10-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_texttext_audiourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttext',
            name='audioURL',
            field=models.URLField(default=''),
        ),
    ]
