# Generated by Django 4.2 on 2023-10-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeData', '0002_alter_texttext_audiourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttext',
            name='audioURL',
        ),
    ]
